"""Add published field to Books model

Revision ID: 3fb5550ebd23
Revises: fad0f485d72c
Create Date: 2025-03-07 11:57:10.076513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb5550ebd23'
down_revision: Union[str, None] = 'fad0f485d72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('books', sa.Column('published', sa.Boolean(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE books SET published = FALSE")
    
    # Then make it not nullable
    op.alter_column('books', 'published', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'published')
    # ### end Alembic commands ###
