version: '3.9'

services:

  db:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 8989:5432
    volumes:
      - fabooks_localdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_USER: mat
      POSTGRES_DB: fabooks


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8999:80
    environment:
      PGADMIN_DEFAULT_EMAIL: mat.redzia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: supersecretpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  fabooks_localdb:
  pgadmin-data: