name: Cypress Tests

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'frontend/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
        python-version: ["3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Install backend dependencies
      working-directory: ./api
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install alembic  # Ensure alembic is installed

    - name: Start backend services
      run: |
        make dev
        sleep 20  # Give the database more time to start

    - name: Start API service
      working-directory: ./api
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        echo $! > api_pid.txt
        sleep 10  # Give the API service time to start

    - name: Verify API service is running
      run: |
        curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ | grep 200 || (echo "API service is not running" && exit 1)

    - name: Populate test data
      run: |
        make populate records=10

    - name: Build with stats
      working-directory: ./frontend
      run: npm run build:stats

    - name: Analyze bundle size
      working-directory: ./frontend
      run: npm run analyze

    - name: Start Angular server
      working-directory: ./frontend
      run: npm start &
      
    - name: Wait for server to be ready
      run: npx wait-on http://localhost:4200 --timeout 60000
      
    - name: Run Cypress tests
      working-directory: ./frontend
      run: npx cypress run --browser chrome

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: frontend/cypress/screenshots
        if-no-files-found: ignore

    - name: Upload videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos
        path: frontend/cypress/videos
        if-no-files-found: ignore

    - name: Stop API service
      if: always()
      run: |
        if [ -f api_pid.txt ]; then
          kill $(cat api_pid.txt) || true
        fi 